KT-35332 "Convert receiver to parameter" ignores invocations of callable objects
JetBrains/kotlin pull request #3510
Opened 2020-06-30 07:00 UTC by t-kameyama

https://youtrack.jetbrains.com/issue/KT-35332

2020-11-17 13:07 UTC, nikitabobko requested changes

2020-11-17 13:07 UTC, nikitabobko commented on idea/src/org/jetbrains/kotlin/idea/refactoring/changeSignature/KotlinChangeSignatureUsageProcessor.kt
> +                        .let { it.extensionReceiver ?: it.dispatchReceiver }
You don't cover all cases:
```
class CallableObject {
    operator fun User.invoke() = println("User.invoke")
}

class User {
    operator fun CallableObject.invoke() = println("CallableObject.invoke")
}

fun User.extFun() {
    val callableObject = CallableObject()
    with(callableObject) {
        this()
        this@extFun()
    }
}
```

2021-02-04 07:59 UTC, t-kameyama commented on idea/src/org/jetbrains/kotlin/idea/refactoring/changeSignature/KotlinChangeSignatureUsageProcessor.kt
> +                        .let { it.extensionReceiver ?: it.dispatchReceiver }
> You don't cover all cases:
> 
> ```
> class CallableObject {
>     operator fun User.invoke() = println("User.invoke")
> }
> 
> class User {
>     operator fun CallableObject.invoke() = println("CallableObject.invoke")
> }
> 
> fun User.extFun() {
>     val callableObject = CallableObject()
>     with(callableObject) {
>         this()
>         this@extFun()
>     }
> }
> ```

Fixed in e31eac1

2021-04-14 10:50 UTC, nikitabobko commented
Merged to new repo:
https://github.com/JetBrains/intellij-kotlin/commit/f97e1a88ac1df90da992141cf42d5dda63c3135d
https://github.com/JetBrains/intellij-kotlin/commit/f98ffbe0a9cccb11c7982205789f803d486179d6

2021-04-14 10:50 UTC, closed without merging