Kotlin-test: floating point assertions.
JetBrains/kotlin pull request #3580
Opened 2020-07-18 18:45 UTC by ReneeVandervelde

Add Float and Double implementations of `assertEquals` and `assertNotEquals` that take a delta for comparing floating point values within a tolerance.

Fixes [KT-8364](https://youtrack.jetbrains.com/issue/KT-8364)

2020-07-28 20:13 UTC, JakeWharton commented
Have you considered adding a default for `delta` so that it only need specified if the error-bound is known? There's more reading on it here: https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#floating-point-comparison

2020-07-29 02:12 UTC, ReneeVandervelde commented
@JakeWharton Yeah I had that thought too. I saw there's [another issue] that discussed adding a general extension for that. @elizarov seemed to think it didn't provide much value there, and I somewhat agree. I left it out here to keep it simple and keep it in-line with most testing frameworks' asserters.

If we did go that route, it would also introduce a little ambiguity to the signature if that parameter were optional, so I might suggest just having separate methods with different names anyway.

[another issue]: https://youtrack.jetbrains.com/issue/KT-14911

2020-07-29 02:21 UTC, JakeWharton commented
Cool just wanted to make sure it had been seen. I learned about it from https://github.com/google/truth/issues/690. I suppose an `assertNear` could be added in the future if it's desired.

2021-03-22 14:07 UTC, qurbonzoda commented
The issue is updated:

> We've discussed this issue and decided to introduce overloads for assertEquals and assertNotEquals taking three numbers, e.g.
```
assertEquals(expected: Double, actual: Double, absoluteTolerance: Double, message: String? = null)
assertNotEquals(illegal: Double, actual: Double, absoluteTolerance: Double, message: String? = null)

// same for Float
```

2021-03-22 14:07 UTC, qurbonzoda commented on libraries/kotlin.test/common/src/main/kotlin/kotlin/test/Assertions.kt
> +@SinceKotlin("1.4")
`@SinceKotlin("1.5")`

2021-03-22 14:09 UTC, qurbonzoda commented on libraries/kotlin.test/common/src/main/kotlin/kotlin/test/Assertions.kt
> +fun assertEquals(expected: Double, actual: Double, delta: Double, message: String? = null) {
Please rename all `delta` arguments name to `absoluteTolerance`

2021-03-22 14:39 UTC, qurbonzoda commented on libraries/kotlin.test/common/src/test/kotlin/kotlin/test/tests/BasicAssertionsTest.kt
> +    }
Please add tests for `NaN` and `Infinite` values

2021-03-23 05:40 UTC, qurbonzoda requested changes
Changes requested

2021-04-05 04:00 UTC, qurbonzoda commented
Moved to https://github.com/JetBrains/kotlin/pull/4275

2021-04-05 04:00 UTC, closed without merging