IR: Add sorting of data class equality checks depending on type
JetBrains/kotlin pull request #4029
Opened 2021-01-12 18:06 UTC by CommanderTvis

Related issue is https://youtrack.jetbrains.com/issue/KT-23184

2021-01-12 18:24 UTC, udalov requested changes
Please add a test with a data class with a bunch of fields of mixed types, with `equals` of non-primitive types having side effects (e.g. append some info to a global string), so that we could check precisely in what order the fields are compared.

2021-01-12 18:24 UTC, udalov commented on compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/util/DataClassMembersGenerator.kt
> +                    else 0
Wouldn't it result in non-primitive fields being compared first, and primitives second? Shouldn't it be the opposite?

2021-01-12 18:29 UTC, udalov commented
As you mention yourself in KT-23184, it's a breaking change in behavior, so as with #4000, we can't push it right away, this needs to be approved by the Language Committee. So it has to be implemented under a `LanguageFeature`, tested both ways, etc.

2021-01-12 18:30 UTC, CommanderTvis commented
@udalov How can I access supported features in that class?

2021-01-12 18:50 UTC, ilmirus commented
@CommanderTvis You should pass an additional parameter to class constructors.

2021-01-12 19:04 UTC, dnpetrov commented
Note that you can still do it uncoditionally if it's definitely known that equality comparisons for all data class property types are "pure" - e.g., `data class AllPure(val stringsArray: Array<String>, val int: Int)`.

2021-01-13 14:38 UTC, CommanderTvis commented
I'm having some problems with building the branch (using `dist` task), so this PR is suspended.

![image](https://user-images.githubusercontent.com/38042667/104466185-80b3b780-55e7-11eb-94c2-7356399d19f0.png)

2021-08-31 10:07 UTC, closed without merging