FIR: ignore deprecated-hidden candidates during resolution
JetBrains/kotlin pull request #4120
Opened 2021-02-15 10:15 UTC by pyos

2021-02-15 12:23 UTC, mglukhikh submitted a review, later dismissed

2021-02-15 14:06 UTC, pyos commented on compiler/fir/resolve/src/org/jetbrains/kotlin/fir/declarations/FirAnnotationUtils.kt
> +        val (_ /*message*/, _ /*replaceWith*/, level) = annotation.argumentMapping?.let { mapping ->
That's not actually correct because annotation arguments are resolved in the same transformer as function calls.

2021-02-15 14:19 UTC, pyos commented on compiler/fir/resolve/src/org/jetbrains/kotlin/fir/declarations/FirAnnotationUtils.kt
> +                mapping.entries.find { (_, value) -> value == parameter }?.key ?: parameter.defaultValue
This doesn't work either, the deserializer does not load default values even for annotation parameters

2021-02-16 10:09 UTC, mglukhikh requested changes
I catched an error while building Kotlin project with FIR:
```
  org.jetbrains.kotlin.fir.FirRuntimeException: Failures detected in FirBodyResolveTransformerAdapter, file: /testProject/core/descriptors/src/org/jetbrains/kotlin/resolve/DescriptorUtils.kt
    at org.jetbrains.kotlin.fir.FirResolveBench.throwFailure(FirResolveBench.kt:333)
    at org.jetbrains.kotlin.fir.FirResolveModularizedTotalKotlinTest.afterPass(FirResolveModularizedTotalKotlinTest.kt:201)
    at org.jetbrains.kotlin.fir.AbstractModularizedTest.runTestOnce(AbstractModularizedTest.kt:165)
    at org.jetbrains.kotlin.fir.FirResolveModularizedTotalKotlinTest.testTotalKotlin(FirResolveModularizedTotalKotlinTest.kt:245)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at junit.framework.TestCase.runTest(TestCase.java:176)
    at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.lambda$runTest$9(KtUsefulTestCase.java:374)
    at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.lambda$invokeTestRunnable$10(KtUsefulTestCase.java:407)
    at com.intellij.testFramework.EdtTestUtilKt.runInEdtAndWait(EdtTestUtil.kt:63)
    at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.invokeTestRunnable(KtUsefulTestCase.java:406)
    at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.runTest(KtUsefulTestCase.java:393)
    at org.jetbrains.kotlin.test.testFramework.KtUsefulTestCase.defaultRunBare(KtUsefulTestCase.java:424)
    at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:18)
    at com.intellij.testFramework.EdtTestUtil$Companion$runInEdtAndWait$1.invoke(EdtTestUtil.kt:13)
    at com.intellij.testFramework.EdtTestUtilKt$runInEdtAndWait$3.run(EdtTestUtil.kt:67)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:419)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
  Caused by: java.lang.RuntimeException: While resolving call R?C|kotlin/with|(when () {
  R|<local>/useOriginal| ->  {
  (this@R|<local>/doBuildOverriddenTreeAsSequence|.R|org/jetbrains/kotlin/descriptors/CallableDescriptor.original| as R|D|)
  }
  else ->  {
  this@R|<local>/doBuildOverriddenTreeAsSequence|
  }
  }
  , <L> = with@fun R|D|.<anonymous>(): <implicit> <kind=EXACTLY_ONCE>  {
  when () {
  R|<local>/set|.R|kotlin/collections/contains|<R|ft<@EnhancedNullability org/jetbrains/kotlin/descriptors/CallableDescriptor, @EnhancedNullability org/jetbrains/kotlin/descriptors/CallableDescriptor?>!|>(this@R|special/anonymous|.R|org/jetbrains/kotlin/descriptors/CallableDescriptor.original|) ->  {
  R?C|kotlin/sequences/emptySequence|()
  }
  else ->  {
  R|<local>/set|.R|kotlin/collections/plusAssign|<R|D|>((this@R|special/anonymous|.R|org/jetbrains/kotlin/descriptors/CallableDescriptor.original| as R|D|))
  R|kotlin/sequences/sequenceOf|<R|D|>(vararg(this@R|special/anonymous|)).plus#((this@R|special/anonymous|.R|org/jetbrains/kotlin/descriptors/CallableDescriptor.overriddenDescriptors| as R|kotlin/collections/Collection<D>|).R|kotlin/collections/asSequence|<R|D|>().flatMap#(<L> = flatMap@fun <anonymous>(it: R|D|): <implicit> {
  R|<local>/it|.doBuildOverriddenTreeAsSequence#()
  }
  ))
  }
  }
  }
  )
    at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirExpressionsResolveTransformer.transformFunctionCall(FirExpressionsResolveTransformer.kt:283)
    at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirBodyResolveTransformer.transformFunctionCall(FirBodyResolveTransformer.kt:115)
    at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirBodyResolveTransformer.transformFunctionCall(FirBodyResolveTransformer.kt:30)
    at org.jetbrains.kotlin.fir.visitors.FirTransformer.visitFunctionCall(FirTransformer.kt:957)
    at org.jetbrains.kotlin.fir.visitors.FirTransformer.visitFunctionCall(FirTransformer.kt:140)
    at org.jetbrains.kotlin.fir.expressions.FirFunctionCall.accept(FirFunctionCall.kt:31)
    at org.jetbrains.kotlin.fir.FirElement$DefaultImpls.transform(FirElement.kt:29)
    at org.jetbrains.kotlin.fir.FirPureAbstractElement.transform(FirPureAbstractElement.kt:11)
    at org.jetbrains.kotlin.fir.visitors.FirTransformerUtilKt.transformSingle(FirTransformerUtil.kt:12)
    at org.jetbrains.kotlin.fir.expressions.impl.FirReturnExpressionImpl.transformResult(FirReturnExpressionImpl.kt:51)
    at org.jetbrains.kotlin.fir.expressions.impl.FirReturnExpressionImpl.transformChildren(FirReturnExpressionImpl.kt:40)
    at org.jetbrains.kotlin.fir.expressions.impl.FirReturnExpressionImpl.transformChildren(FirReturnExpressionImpl.kt:25)
    at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirExpressionsResolveTransformer.transformExpression(FirExpressionsResolveTransformer.kt:63)
    at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirBodyResolveTransformer.transformExpression(FirBodyResolveTransformer.kt:97)
    at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirControlFlowStatementsResolveTransformer.transformJump(FirControlFlowStatementsResolveTransformer.kt:189)
    at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirControlFlowStatementsResolveTransformer.transformReturnExpression(FirControlFlowStatementsResolveTransformer.kt:210)
    at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirBodyResolveTransformer.transformReturnExpression(FirBodyResolveTransformer.kt:354)
    at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirBodyResolveTransformer.transformReturnExpression(FirBodyResolveTransformer.kt:30)
    at org.jetbrains.kotlin.fir.visitors.FirTransformer.visitReturnExpression(FirTransformer.kt:1033)
    at org.jetbrains.kotlin.fir.visitors.FirTransformer.visitReturnExpression(FirTransformer.kt:140)
    at org.jetbrains.kotlin.fir.expressions.FirReturnExpression.accept(FirReturnExpression.kt:26)
    at org.jetbrains.kotlin.fir.FirElement$DefaultImpls.transform(FirElement.kt:29)
    at org.jetbrains.kotlin.fir.FirPureAbstractElement.transform(FirPureAbstractElement.kt:11)
    at org.jetbrains.kotlin.fir.expressions.FirExpressionUtilKt.transformStatementsIndexed(FirExpressionUtil.kt:121)
    at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirExpressionsResolveTransformer.transformBlockInCurrentScope$resolve(FirExpressionsResolveTransformer.kt:308)
    at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirExpressionsResolveTransformer.transformBlock(FirExpressionsResolveTransformer.kt:299)
    at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirBodyResolveTransformer.transformBlock(FirBodyResolveTransformer.kt:126)
    at org.jetbrains.kotlin.fir.resolve.transformers.body.resolve.FirBodyResolveTransformer.transformBlock(FirBodyResolveTransformer.kt:30)
    at org.jetbrains.kotlin.fir.visit [...]

2021-03-17 08:54 UTC, closed without merging