IR: preserve argument evaluation order more carefully
JetBrains/kotlin pull request #4497
Opened 2021-07-12 13:34 UTC by pyos

1. receivers should be evaluated before named arguments;
 2. just because an argument has no side effects doesn't mean it is not affected by the other arguments' side effects - in that case it should still be evaluated in source order.

 #KT-47660 Fixed

2021-07-12 13:34 UTC, pyos commented on compiler/ir/ir.psi2ir/src/org/jetbrains/kotlin/psi2ir/generators/CallGenerator.kt
>              this is IrClassReference ||
note: technically those can have side effects due to class initialization, so maybe this is wrong

2021-07-12 13:51 UTC, dnpetrov commented
@mglukhikh please, take a look at https://github.com/JetBrains/kotlin/pull/4497/commits/f3cdf19ea2c7bdbcb63853292b2b8bf6df7653b2#diff-b0333afff787be679b651253d6311c2686a5663a7e50d651c6c50c48943dd194R295

2021-07-12 13:55 UTC, dnpetrov commented
PSI2IR part - LGTM.

2021-07-12 14:25 UTC, mglukhikh requested changes
Fir2IrTextTestGenerated.testDeprecated fails in your branch. Please fix (looks like something is broken in annotation handling).

2021-07-12 14:35 UTC, pyos commented
fixed

2021-07-12 14:53 UTC, mglukhikh commented
Looks ok, I'll check whether bootstrap can be built with this branch.

2021-07-12 15:43 UTC, mglukhikh approved these changes

2021-07-13 13:42 UTC, dnpetrov commented
1. Please, add missing generated JS tests.

2. There were some test failures, in particular:
- JsCodegenBoxTestGenerated$ArgumentOrder.testSingleSideEffect - most likely a bug in legacy JS BE, use `IGNORE_BACKEND: JS` directive 
- Fir2IrTextTestGenerated$FirProblems.testDeprecated - please, update testData accordingly.

2021-07-13 16:06 UTC, dnpetrov commented
Nevermind, I'll fix the bureaucracy myself.

2021-07-13 18:10 UTC, pyos commented
>Fir2IrTextTestGenerated$FirProblems.testDeprecated - please, update testData accordingly.

That should already be fixed, see above

2021-07-14 10:17 UTC, dnpetrov commented
master (1.6-M1): https://github.com/JetBrains/kotlin/commit/3dc7b6c3eec1ceee1917563ca9e8e71a12539d08
1.5.30-M1: https://github.com/JetBrains/kotlin/commit/afc0726ad66248b8a16cdfb1a00a7af3f24cc8cb
1.5.30: https://github.com/JetBrains/kotlin/commit/52ca6bcca84a2f75819f11bf16f7279cd0fa42fe

2021-07-14 10:17 UTC, closed without merging