Serialization: Serializable meta annotation
JetBrains/kotlin pull request #4583
Opened 2021-09-17 00:04 UTC by rsinukov

https://youtrack.jetbrains.com/issue/KTOR-2704

Add handling for (not yet released) kotlinx.serialization `@MetaSerializable`

2021-09-17 05:54 UTC, Repoman124 requested changes
#4583

2021-09-17 05:55 UTC, Repoman124 reviewed
I'm attempting my first pull

2022-02-08 16:25 UTC, rsinukov commented on plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/ir/GeneratorHelpers.kt
> +                    if (property.type.toIrType().isKClass()) kClassExprToJClassIfNeeded(startOffset, endOffset, it) else it
done

2022-02-08 16:25 UTC, rsinukov commented on plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/resolve/NamingConventions.kt
> +    internal val metaSerializableAnnotationFqName = FqName("kotlinx.serialization.MetaSerializable")
done

2022-02-08 16:26 UTC, rsinukov commented on plugins/kotlin-serialization/kotlin-serialization-compiler/src/org/jetbrains/kotlinx/serialization/compiler/backend/ir/SerializableIrGenerator.kt
> +    private val IrClass.isInternalSerializable: Boolean get() = this.descriptor.isInternalSerializable
done

2022-02-08 16:26 UTC, rsinukov commented on plugins/kotlin-serialization/kotlin-serialization-compiler/testData/boxIr/metaSerializable.kt
> +//    val info = Project3.serializer().descriptor.annotations.filterIsInstance<MySerializableWithInfo>().first()
sorry, fotgot to delete it. done

2022-02-08 16:26 UTC, rsinukov commented on plugins/kotlin-serialization/kotlin-serialization-compiler/testData/boxIr/metaSerializable.kt
> +class Project3(val name: String, val language: String)
Why only in runtime? 
Added tests to this repo.

2022-03-25 16:00 UTC, sandwwraith approved these changes

2022-03-25 16:07 UTC, merged