FE: Type Attributes
JetBrains/kotlin pull request #4618
Opened 2021-10-13 19:54 UTC by irenedea

2021-10-20 05:04 UTC, irenedea commented
Commit 7879193 has caused the following exception when compiling (specifically, I am doing `./gradlew dist`). @demiurg906, do you know what would cause this? It seems to stem from fir calls.
```
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/reflect/jvm/internal/impl/extensions/ProjectExtensionDescriptor
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at kotlin.reflect.jvm.internal.impl.types.extensions.TypeAttributeTranslators.<clinit>(TypeAttributeTranslators.kt)
        at kotlin.reflect.jvm.internal.impl.serialization.deserialization.DeserializationComponents.<init>(context.kt:58)
        at kotlin.reflect.jvm.internal.impl.load.kotlin.DeserializationComponentsForJava.<init>(DeserializationComponentsForJava.kt:73)
        at kotlin.reflect.jvm.internal.impl.load.kotlin.DeserializationComponentsForJavaKt.makeDeserializationComponentsForJava(DeserializationComponentsForJava.kt:188)
        at kotlin.reflect.jvm.internal.impl.load.kotlin.DeserializationComponentsForJava$Companion.createModuleData(DeserializationComponentsForJava.kt:119)
        at kotlin.reflect.jvm.internal.impl.descriptors.runtime.components.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:32)
        at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:36)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:35)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(KDeclarationContainerImpl.kt:35)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:50)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:48)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt:48)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$supertypes$2.invoke(KClassImpl.kt:125)
        at kotlin.reflect.jvm.internal.KClassImpl$Data$supertypes$2.invoke(KClassImpl.kt:124)
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:93)
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getSupertypes(KClassImpl.kt:124)
        at kotlin.reflect.jvm.internal.KClassImpl.getSupertypes(KClassImpl.kt:254)
        at kotlin.reflect.full.KClasses.getAllSupertypes(KClasses.kt:193)
        at kotlin.reflect.full.KClasses.getAllSuperclasses(KClasses.kt:223)
        at org.jetbrains.kotlin.fir.checkers.generator.CheckersConfiguration$1.invoke(CheckersConfiguration.kt:23)
        at org.jetbrains.kotlin.fir.checkers.generator.CheckersConfiguration$1.invoke(CheckersConfiguration.kt:21)
        at org.jetbrains.kotlin.fir.checkers.generator.CheckersConfigurationKt.bfs(CheckersConfiguration.kt:49)
        at org.jetbrains.kotlin.fir.checkers.generator.CheckersConfigurationKt.access$bfs(CheckersConfiguration.kt:1)
        at org.jetbrains.kotlin.fir.checkers.generator.CheckersConfiguration.<init>(CheckersConfiguration.kt:21)
        at org.jetbrains.kotlin.fir.checkers.generator.CheckersConfigurator.build(CheckersConfigurator.kt:30)
        at org.jetbrains.kotlin.fir.checkers.generator.CheckersConfiguratorKt.generateCheckersComponents(CheckersConfigurator.kt:40)
        at org.jetbrains.kotlin.fir.checkers.generator.MainKt.main(Main.kt:23)
Caused by: java.lang.ClassNotFoundException: kotlin.reflect.jvm.internal.impl.extensions.ProjectExtensionDescriptor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 45 more

```

2021-11-05 19:47 UTC, irenedea commented on core/descriptors/src/org/jetbrains/kotlin/types/KotlinTypeFactory.kt
> +    fun simpleTypeWithNonTrivialMemberScope(
Addressed in 27d9f87

2021-11-05 19:48 UTC, irenedea commented on compiler/frontend/src/org/jetbrains/kotlin/resolve/calls/inference/BuilderInferenceUtil.kt
>      override fun replaceAnnotations(newAnnotations: Annotations) = this
Addressed in 
e06bd13

2021-11-11 08:11 UTC, demiurg906 requested changes

2021-11-11 08:11 UTC, demiurg906 commented on compiler/frontend/src/org/jetbrains/kotlin/frontend/di/injection.kt
> +    useInstance(TypeAttributeTranslators(moduleContext.project))
It's better to use `useImpl<TypeAttributeTranslators>()` here. `project` will be injected automatically

2021-11-11 08:11 UTC, demiurg906 commented on core/descriptors/src/org/jetbrains/kotlin/types/CustomAnnotationTypeAttribute.kt
> +    override fun equals(other: Any?): Boolean {
Where is `hashCode`?

2021-11-11 08:11 UTC, demiurg906 commented on .idea/artifacts/kotlin_test_wasm_js_1_6_255_SNAPSHOT.xml
> +      <element id="module-output" name="kotlin.kotlin-test.kotlin-test-wasm.jsMain" />
Please remove this from commit

2021-11-11 08:11 UTC, demiurg906 commented on compiler/ir/ir.tree/src/org/jetbrains/kotlin/ir/types/IrTypeSystemContext.kt
> +        return emptyList() // TODO: Ir does not currently support custom non-annotation attributes.
It's not `TODO`. IR backed should not support attributes by design

2021-11-11 08:11 UTC, demiurg906 commented on compiler/resolution.common/src/org/jetbrains/kotlin/resolve/calls/inference/model/MutableConstraintStorage.kt
> +                        if (previousConstraint.type.getCustomAttributes() == constraint.type.getCustomAttributes())
Maybe it's better to replace `getCustomAttributes` with `hasCustomAttributes` and only then filter attributes?

2021-11-11 08:20 UTC, demiurg906 commented
@irenedea Could you please rebase your branch to the next review iteration and squash most of the commits to cleanup history?

2021-12-16 02:52 UTC, irenedea commented on core/descriptors/src/org/jetbrains/kotlin/types/TypeSubstitution.kt
> +        if (newAnnotations is FilteredAnnotations && newAnnotations.isEmpty()) Annotations.EMPTY else newAnnotations
There is a strange(?) implementation of FilteredAnnotations.isEmpty() that some of the tests rely on: https://github.com/JetBrains/kotlin/blob/master/core/descriptors/src/org/jetbrains/kotlin/descriptors/annotations/Annotations.kt#L71

2022-01-10 07:20 UTC, demiurg906 commented
Merged manually

2022-01-10 07:20 UTC, closed without merging