JVM_IR: do not mangle default property accessor of annotation class
JetBrains/kotlin pull request #4669
Opened 2021-12-02 04:27 UTC by scaventz

issue: [KT-49998](https://youtrack.jetbrains.com/issue/KT-49998)

2021-12-04 00:42 UTC, Mtan6666666 commented
Trust wallet

2021-12-08 17:51 UTC, udalov commented on compiler/testData/codegen/box/annotations/annotationDefaultValueOfUnsigned.kt
> +    val default1 = A::class.java.getDeclaredAnnotation(Ann1::class.java).value
`Class.getDeclaredAnnotation` is missing on JDK6 and older versions of Android, so the corresponding tests (`compiler/tests-different-jdk`, `compiler/android-tests`) are failing. Let's use `Class.getAnnotation` instead

2021-12-08 17:56 UTC, udalov commented
The change feels strange because we already don't mangle annotation property accessors. It's just `value` in the bytecode, without the mangling suffix. Which hints that the root problem might be located elsewhere.

I remember similar problems with other cases when corresponding property of accessors (`IrSimpleFunction.correspondingProperyt`) was accidentally lost during IR transformation. Does it seem like something that's happening here? In that case, it'd be better to track where it's being lost and fix that instead, because it may cause other problems.

2021-12-17 20:08 UTC, ilmirus requested changes

2021-12-17 20:08 UTC, ilmirus commented on compiler/testData/codegen/box/annotations/annotationDefaultValueOfUnsigned.kt
> +class A
Can you, please, also test an inline class other than unsigned integral type?

2021-12-17 20:11 UTC, ilmirus commented on compiler/testData/codegen/box/annotations/annotationDefaultValueOfUnsigned.kt
> +class A
Ah, nevermind. Usual inline classes are not allowed inside annotation.

2021-12-17 20:11 UTC, ilmirus approved these changes

2021-12-17 20:13 UTC, udalov commented
The change looks good to me too, but I need some time to investigate what exactly is the issue with inline classes compared to non-inline classes.

2021-12-20 17:14 UTC, scaventz commented
Sorry for not providing detailes ealier.
As far as I know, in `MemoizedInlineClassReplacements:78`, because the inline return type of getValue meets the condition

```kotlin
val IrFunction.hasMangledReturnType: Boolean
    get() = returnType.isInlineClassType() && parentClassOrNull?.isFileClass != true
```

, the `backingField` get accidentally lost in `createMethodReplacement` method (used to compute default value of annotation in `getAnnotationDefaultValueExpression` method of `FunctionCodegen`).

It seems the method `createMethodReplacement` is mainly just mangle the name of function `getValue` and maybe unnecessary, because in the end the mangled name is never adopted( see method `mapSignature`of `MethodSignatureMapper.kt`)
But even if the mangle process can be avoid here, I agree to do a simple and intuitive fix first, like this PR does.

2021-12-21 23:35 UTC, merged

2021-12-21 23:35 UTC, udalov commented
Thanks for the explanation, it makes sense and indeed seems like the simplest fix. Merged to master, will be released in 1.6.20. Thank you for the contribution!