K2 JVM: Fix wrong action in val declarations conflicting
JetBrains/kotlin pull request #4986
Opened 2022-10-14 19:16 UTC by lfkdsk

K2 compiler allows val redeclaration, Fixes: https://youtrack.jetbrains.com/issue/KT-54405/K2-compiler-allows-val-redeclaration

``` kotlin
fun main(args: Array<String>) {

    val someVal = "One" //Highlighted with e: [REDECLARATION] Conflicting declarations: val someVal: String, val someVal: Int
    val someVal = 42//Highlighted with e: [REDECLARATION] Conflicting declarations: val someVal: String, val someVal: Int

    println (someVal)
}
```

2022-10-18 12:41 UTC, KvanTTT requested changes
Thanks for the contribution!

But the header of this PR is confusing. This redeclaration is not JVM-specific diagnostics, please remove `JVM`.

Also, please fix other remarks.

2022-10-18 12:41 UTC, KvanTTT commented on compiler/fir/checkers/src/org/jetbrains/kotlin/fir/analysis/checkers/declaration/FirConflictsChecker.kt
> +    private fun checkBlock(body: FirBlock, inspector: DeclarationInspector) {
The method doesn't check in the following case:

```kt
fun main(b: Boolean) {
    if (b) {
        val someVal2 = 2
        val someVal2 = "Two"
    }
}
```

Please consider more cases.

2022-10-18 15:24 UTC, KvanTTT commented
Also, there are a lot of failed tests (at least `FirOldFrontendDiagnosticsTestGenerated`). Please fix them, they can run locally.

2022-10-18 19:40 UTC, lfkdsk commented
Fix test and fix other original testData result.

2022-10-25 06:26 UTC, lfkdsk commented
@KvanTTT

2022-10-31 19:26 UTC, KvanTTT commented
Thank you for the contribution, it will be merged eventually later. Sorry, but I'm busy with more priority tasks for now.

2023-03-21 20:28 UTC, KvanTTT reviewed
Thanks for the contribution but this bug was eventually fixed by https://github.com/JetBrains/kotlin/commit/e49bb1fe37950a540e312bb6be020e46af8dcc38

2023-03-21 20:28 UTC, closed without merging