Grammar fixes in docs of JVM annotations
JetBrains/kotlin pull request #4997
Opened 2022-10-20 14:18 UTC by mickeelm

2024-11-25 08:44 UTC, mickeelm commented
Over two years now. My OCD wants me to close this :) Should I or does anyone want to have a look at it?

2024-12-06 14:11 UTC, fzhinkin commented on libraries/stdlib/common/src/kotlin/JvmAnnotationsH.kt
> + * Adding and removing the annotation is a binary incompatible change, since methods and functions of inline classes are mangled.
This sentence changed its [intended] meaning. Adding/removing the annotation affects not only member functions of the annotated class, but also all other functions accepting that class a parameter: https://godbolt.org/z/z8YYjdfaP

2024-12-06 14:15 UTC, fzhinkin commented on libraries/stdlib/common/src/kotlin/JvmAnnotationsH.kt
> + * It may be helpful only if the declaration seems to be inconvenient to use from Java without wildcard.
`a wildcard`?

2024-12-06 14:18 UTC, fzhinkin requested changes
@mickeelm, sorry for the delay with review. 
Please rebase the branch on the recent master.

2025-01-31 12:15 UTC, mickeelm commented
@fzhinkin My turn to apologize, seems I have missed the notification of this. I'll fix this within the next few days...

2026-08-25 14:41 UTC, fzhinkin commented
Feel free to reopen the PR once ready to continue work on it.

2026-08-25 14:41 UTC, closed without merging