Fix indy lambdas with extension and context receivers
JetBrains/kotlin pull request #5021
Opened 2022-11-12 13:03 UTC by mcpiroman

KT-53957 Fixed
KT-52874 likely fixed

Parameters were ordered incorrectly: [extension receiver, context receivers, regular parameters] instead of [context receivers, extension receiver, regular parameters].

Wouldn't it be reasonable to have a separate list of context parameters (instead of `contextReceiverParametersCount`), the same as `extensionReceiverParameter` is separate in IR?

2022-11-29 22:59 UTC, udalov commented
> Wouldn't it be reasonable to have a separate list of context parameters (instead of `contextReceiverParametersCount`), the same as `extensionReceiverParameter` is separate in IR?

As a part of [KT-53696](https://youtrack.jetbrains.com/issue/KT-53696), we're rather considering merging all parameters into one list, so that many places like this won't need to handle three kinds of parameters. But it's still being discussed.

2022-12-15 16:26 UTC, strangepleasures requested changes
Thanks for contributing your fix. Please revert the changes in the import sections of the auto-generated files. Otherwise looks great.

2022-12-15 16:26 UTC, strangepleasures commented on compiler/fir/fir2ir/tests-gen/org/jetbrains/kotlin/test/runners/codegen/FirBlackBoxCodegenTestGenerated.java
> -import org.jetbrains.kotlin.test.util.KtTestUtil;
Please, don't modify the order of imports in the auto-generated files; that causes some build checks to fail. Make sure that you don't have "Before Commit" actions enabled.

2022-12-16 11:52 UTC, strangepleasures commented
@mcpiroman Please revert formatting in FirBlackBoxCodegenTestGenerated and IrBlackBoxCodegenTestGenerated as well. Sorry for not being explicit about that.

2022-12-16 16:47 UTC, merged

2024-02-17 10:08 UTC, Ponchest commented
Dejar de seguir mi información ya r colocado denuncio