[KT-57607] Fix performance of ArrayList.addAll methods in JS stdlib
JetBrains/kotlin pull request #5116
Opened 2023-03-27 18:21 UTC by DeoTimeTheGithubUser

Relating issue: [KT-57607](https://youtrack.jetbrains.com/issue/KT-57607/MutableList.addAll-has-UNACCEPTABLE-performance-on-Kotlin-JS-legacy-IR)

2023-03-27 20:06 UTC, ilya-g requested changes

2023-03-27 20:06 UTC, ilya-g commented on libraries/stdlib/js/src/kotlin/collections/ArrayList.kt
> +        dummy.push.apply(array, elements.toTypedArray<Any?>())
AFAIK, there was some limitation on how many parameters can be spread using this approach, so it may fail on large `elements` collection

2023-03-27 22:28 UTC, robledo6 commented on libraries/stdlib/js/src/kotlin/collections/ArrayList.kt
> +    private val dummy = js("[]")
Nasa. Más

2023-03-28 01:49 UTC, DeoTimeTheGithubUser commented
Thanks, I've changed it to iterating over the elements instead of spreading into a method

2023-03-29 06:12 UTC, ilya-g requested changes

2023-03-29 06:12 UTC, ilya-g commented on libraries/stdlib/js/src/kotlin/collections/ArrayList.kt
> +        elements.forEach(array.asDynamic()::push)
Would be better to expand the array by setting its length and then fill elements manually.

2023-03-29 06:12 UTC, ilya-g commented on libraries/stdlib/js/src/kotlin/collections/ArrayList.kt
> +            array.asDynamic().splice(i, 0, element)
Moving array tail on each element insertion would result in quadratic complexity.

2023-03-29 06:12 UTC, ilya-g commented on libraries/stdlib/js/src/kotlin/collections/ArrayList.kt
> +        return jsArrayPrototype.slice.call(array)
It doesn't seem that jsArrayPrototype is now used anywhere except this function. Does it make sense to extract it then to a variable?

2023-04-03 03:58 UTC, DeoTimeTheGithubUser commented
Sorry for the delay, will get to these tmr

2023-04-05 07:14 UTC, ilya-g approved these changes
Neat. Let's wait for a CI run and I'll merge it after that.

2023-04-05 07:39 UTC, LouisCAD commented
Can we have a benchmark to compare the performance before/after, and compared to calling add multiple times?

2023-04-05 16:12 UTC, ilya-g commented
@LouisCAD I'd leave that as an exercise for the reader :)

2023-04-05 18:18 UTC, merged

2023-04-06 13:32 UTC, LouisCAD commented
Is there a directory for existing Kotlin/JS benchmarks where I could submit a PR?

I'd also be curious about if skipping splice would have any beneficial effect performance wise when the index is zero, and how much the impact would be for the non zero case.

2023-04-08 15:20 UTC, ilya-g commented
No, we don't have a directory with stdlib benchmarks.
Usually we create a one-off repository when we need to benchmark some alternatives where we compare different implementations. For benchmarking Kotlin/JS, we use `kotlinx.benchmark`. For example: https://github.com/qurbonzoda/StringBuilderBenchmarks/blob/master/build.gradle