KT-54363 Allow using reified types for catch parameters
JetBrains/kotlin pull request #5194
Opened 2023-09-28 18:03 UTC by kralliv

Allow using reified types for catch parameters

```kotlin
inline fun <reified E : Throwable> fails(block: () -> Unit): E {
    try {
        block()
    } catch (exception: E) {
        return exception
    }
    
    error("should have failed")
}
```

For more context read the comment in the [YouTrack Issue](https://youtrack.jetbrains.com/issue/KT-54363/Allow-using-reified-types-for-catch-parameters).

### Kotlin/JVM

In Bytecode catch clauses are described by two things: an entry in the exception table and a handler entrypoint in the instructions.

```
TRYCATCHBLOCK L0 L1 L2 java/lang/Throwable

L0:         // start
  [...]
L1:         // end
  NOP
L2:         // handler
  LINENUMBER 4 L2
 FRAME FULL [] [java/lang/Throwable]
  ASTORE 0
L3:
  [...]
```

The entry consists out of three labels and type. The first two labels describe the effective range, where exceptions of the specified type are to be caught. If caught, the exception is pushed onto the stack and the execution jumps to the third label. The third label is the handler. Its responsibility its to the receive and store the exception on top of the stack. It is not to be confused with the catch body, which follows with the next label.

The goal is to store information about where type parameters are and replace them with the actual type once known.

The simplest solution would be to store the type parameter in the exception table itself. While the type is a string, it cannot be used for storing the type parameter. The type is loaded eagerly during class initialization. Storing for example `[T?` would lead to a ClassNotFound. This means, that Bytecode does not allow for the exception table to be used for storing a reification markers directly. 

Instead, I opted to reuse the current reification marker system targeted at the `ASTORE` instruction in the handler.

```
TRYCATCHBLOCK L0 L1 L2 java/lang/Throwable

L0:         // start
  [...]
L1:         // end
  NOP
L2:         // handler
  LINENUMBER 4 L2
 FRAME FULL [] [java/lang/Throwable]
  BIPUSH 7
  LDC "E"
  INVOKESTATIC kotlin/jvm/internal/Intrinsics.reifiedOperationMarker (ILjava/lang/String;)V
  ASTORE 0
L3:
  [...]
```

The `ASTORE` instruction can be directly traced back to its entry in the exception table via the label of the handler.

During inlining, if the type is known, the instruction is left as is. Instead, the type in the exception table is replaced by the actual type and the marker is removed. If the type parameter is just another type parameter, the value of `LDC` instruction is modified accordingly instead, like it is done in the case of all the others reified operations.

### Kotlin/Other

As suspected by Roman Elizarov in the issue, the IR inliner seems to be able to correctly inline the catch clause parameter. All of my test cases worked out of the box, once I had disabled the error diagnostics.

### Diagnostics

I updated the diagnostics code to only forbid reified types in catch clauses in versions lower than 2.0 and changed the messages accordingly. This way, red code will be preserved for older version.

2024-01-29 19:58 UTC, kralliv commented
Any updates on this? Is this indirectly covered by [KT-64570](https://youtrack.jetbrains.com/issue/KT-64570) and therefor not relevant anymore?

2024-01-29 21:26 UTC, udalov commented
@kralliv Sorry for the delay, and thank you for the ping. It's still relevant but we're pretty busy with finishing the K2 compiler right now. Moreover, we have an embargo on new language features in 2.0, so the earliest this feature can be enabled is Kotlin 2.1. Your change seems fine, but I'll have to review it in detail a little bit later.

2024-01-30 16:11 UTC, kralliv commented
Absolutely no problem. I'm well aware that finishing K2 is a churn.

2024-12-02 21:21 UTC, kralliv commented
@udalov Now that the 2.1 is out, I have returned ;)
I rebased the changes on the latest revision of the master branch and ran the tests again. The assigned version of the language feature is of course still entirely provisional.

2025-04-04 11:35 UTC, udalov commented
Sorry for the delay. I've rebased on master and made a few adjustments:
* Remove changes in K1, as the current policy is preferably to avoid any changes in K1 behavior
* Use `requireFeatureSupport` in the checker to report `UNSUPPORTED_FEATURE`, and remove `REIFIED_TYPE_IN_CATCH_CLAUSE` which is not used anymore
* Change language feature type from `BUG_FIX` to `OTHER`, because it brings a new functionality and does not prohibit anything
* Minor changes in formatting

I'll make sure to get a green build and will continue with testing and merging the feature.

2025-04-04 12:56 UTC, kralliv commented
No problem, really. Thank you for the rundown of your changes. Good to know about the K1 policy and I'll keep the `requireFeatureSupport` in mind.
If you find anything that needs to be worked out still, do tell me and I'll have a look at it.

2025-05-08 07:06 UTC, demiurg906 requested changes

2025-05-08 07:06 UTC, demiurg906 commented on compiler/fir/analysis-tests/testData/resolve/catchParameter.kt
> +// LANGUAGE: +AllowReifiedTypeInCatchClause
Please add an additional test with this feature disabled to check that the error is still reported for 2.2 and lower

2025-05-08 07:52 UTC, udalov commented on compiler/fir/analysis-tests/testData/resolve/catchParameter.kt
> +// LANGUAGE: +AllowReifiedTypeInCatchClause
There is `compiler/testData/diagnostics/tests/controlStructures/catchReifiedTypeForbidden.kt`

2025-05-08 08:15 UTC, demiurg906 commented on compiler/fir/analysis-tests/testData/resolve/catchParameter.kt
> +// LANGUAGE: +AllowReifiedTypeInCatchClause
Oh, indeed. I've missed it

2025-05-08 08:15 UTC, demiurg906 submitted a review, later dismissed

2025-06-10 12:54 UTC, udalov commented
I've rebased on a fresh master and added a couple of tests. The feature is targeted to be released as experimental in 2.2.20 and hopefully stable in 2.4.

2025-06-18 17:44 UTC, udalov commented
Merged in 8a5ee71488207d795ef778b5b36d312124db9fae (+ 2e7e25c8a27cdad8417d0d1af3f09458192e954b, e68be9f2d403efb84d5bfe6691eb03a10e57a5b4, ba6eb858f835eeab1b9008dda9076227d84514b7). Thank you for the contribution. :)

2025-06-18 17:44 UTC, closed without merging

2025-06-19 01:33 UTC, kralliv commented
@udalov That's great! Thank you for all your time and effort :)