fix KT-65156
JetBrains/kotlin pull request #5249
Opened 2024-01-20 10:08 UTC by k163377

SSIA
https://youtrack.jetbrains.com/issue/KT-65156

2024-01-20 10:11 UTC, k163377 commented on compiler/testData/codegen/box/reflection/callBy/inlineClassDefaultArguments.kt
I considered splitting and organizing the test, but decided against it for now.
However, I think that we should create an `inlineClass` directory like `call` and prepare test cases for each type to be wrapped.

2024-01-22 12:41 UTC, udalov requested changes

2024-02-08 14:57 UTC, udalov approved these changes

2024-02-09 17:57 UTC, udalov commented
Merged in a5bf8787a128663e892d8da84befc022ac8fb0a4. Thank you for the contribution!

2024-02-09 17:57 UTC, closed without merging