[Test] Modified classes declared as inline class to value class
JetBrains/kotlin pull request #5324
Opened 2024-06-29 12:36 UTC by k163377

This is due to the following comments received in a previously submitted PR.
https://github.com/JetBrains/kotlin/pull/5269#discussion_r1500530556

Since this is a preparation for the addition of a new test, the scope of the correction is limited to `compiler/testData/codegen/box/reflection`.

2024-07-01 11:34 UTC, udalov approved these changes

2024-07-01 13:49 UTC, udalov requested changes

2024-07-01 14:04 UTC, k163377 commented on compiler/testData/codegen/box/reflection/typeOf/inlineClasses.kt
> +value class Z(val value: String)
Fixes have been pushed.
There were other test that targeted other than the `JVM`, so that have been fixed at the same time.
0245ec0

2024-07-01 14:39 UTC, udalov approved these changes

2024-07-02 08:26 UTC, udalov commented
Fixed in 5f201fe4240d23b27392b4d3c105b9ff20580c2f, thank you!

2024-07-02 08:26 UTC, closed without merging